vich_uploader:
    db_driver: orm

    mappings:
        projets:
            uri_prefix: /images/projets
            upload_destination: '%kernel.project_dir%/public/images/projets'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
